# Generated by Django 3.0.5 on 2020-04-10 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servico',
            old_name='sevico',
            new_name='servico',
        ),
    ]
